version: '3'
services:
  web:
    image: $IMAGE_DEV
    user: $USER
    volumes:
      - ./app:/app
      - $PWD/passwd:/etc/passwd:ro
    working_dir: /app
    command: "npm run start"
    ports:
      - "3000:3000"